### ISSUE TITLE
Sprint 5 of 21.1 scheduler crashes if scrolling="virtual"

### ISSUE THREAD

**Issue by bobskigit** [DevExpress/DevExtreme#16054]
In the latest Sprint 5 of 21.1 the scheduler crashes if you try to use scrolling="virtual". If you remove the virtual scrolling its OK.

The error is 

core.js:6063 ERROR TypeError: Cannot read property 'dateTable' of undefined
    at layout.js:226
    at d.DateTableLayoutBase [as constructor] (layout.js:243)
    at d.L [as render] (preact.module.js:1)
    at $ (preact.module.js:1)
    at m (preact.module.js:1)
    at $ (preact.module.js:1)
    at m (preact.module.js:1)
    at $ (preact.module.js:1)
    at Module.M (preact.module.js:1)
    at TimelineDateTableLayout.value (component.js:412)

Its a simple scheduler using a set of grouped resources

**Comment by AryamnovEugeniy** [comment]
Hello!

Please, accept my apologies for a late response.
I could not reproduce this issue. But we fixed a similar bug while working on [21.1 Sprint 6](https://github.com/DevExpress/DevExtreme/releases/tag/21.1.1-sprint.6). Could you please check whether the issue still persists? If it does, could you update [my sample ](https://codepen.io/pin361/pen/oNYjBrg?editors=0010) so that the problem would be reproduced?

Regards,
Eugeniy

**Comment by bobskigit** [comment]
I have tried it using the latest Sprint 7 and that problem is fixed.

 

However if you load the resources from a datasource rather than an Array it crashes. Should I add this as a new Issues?

 

Regards

 

Bob Lamb

**Comment by AryamnovEugeniy** [comment]
Thank you for your interest in our product! There is no need in creating a separate issue. But I could not reproduce the problem with dataSource you described. Could you update my sample (https://codepen.io/EugeniyAryamnov/pen/YzpQdor?editors=0010) so that it would be reproduced? It will help us solve this sooner.

**Comment by bobskigit** [comment]
I’ll describe the problem as it is difficult to produce a small example as its part of a large Angular project.

 

If you load the sources from a service like this

 

<dxi-resource fieldExpr="channelId"  displayExpr="name" [allowMultiple]="false"

    [dataSource]="displayitems">

  </dxi-resource>

 

datasource is loaded like this

 

loadResources {

 

this.resourceService.load ().subscribe( items => {

 

this.displayitems = items;

 

}}

 

You get this error (if you turn virtual scrolling on)

 

vendor.js:115284 ERROR TypeError: Cannot read property 'key' of undefined

    at vendor.js:373220

    at Array.map (<anonymous>)

    at viewFunction (vendor.js:373216)

    at p.GroupPanelVerticalLayout [as constructor] (vendor.js:373243)

    at p.M [as render] (vendor.js:35142)

    at T (vendor.js:35142)

    at b (vendor.js:35142)

    at T (vendor.js:35142)

    at b (vendor.js:35142)

    at T (vendor.js:35142)

 

 

Regards

Bob Lamb

**Comment by AryamnovEugeniy** [comment]
I could not reproduce this issue based on your example. Could you share with me the resources (`this.displayitems = items;`) you use when you get this error?

**Comment by bobskigit** [comment]
This is smallest example to show it..

 

HTML

<dx-scheduler [dataSource]="scheduleSource" currentView="timelineDay" [crossScrollingEnabled]="true" [views]='["timelineDay"]'

  [showAllDayPanel]='false' [groups]="['channelId']" [currentDate]="currentDate">

  <dxi-resource fieldExpr="channelId" displayExpr="name" [allowMultiple]="false" [dataSource]="displaychannels">

  </dxi-resource>

  

<dxo-scrolling mode="virtual" type="both"></dxo-scrolling>

</dx-scheduler>

 

TS

import { Component, OnInit, ViewChild } from '@angular/core';

import { DxSchedulerComponent } from 'devextreme-angular';

import { Observable } from 'rxjs';

 

@Component({

  selector: 'app-sc',

  templateUrl: './sc.component.html',

  styleUrls: ['./sc.component.scss']

})

export class ScComponent implements OnInit {

  @ViewChild(DxSchedulerComponent) scheduler: DxSchedulerComponent;

 

  currentDate: Date = new Date(2021, 4, 25);

  scheduleSource = [];

  displaychannels = [];

 

  observable: Observable<any> = new Observable(observer => {

    setTimeout(() => {

      const items = [

        { name: 'Channel 1', channelId: 1 },

        { name: 'Channel 2', channelId: 2 }

      ];

      observer.next(items);

      observer.complete(); // to show we are done with our processing

    }, 2000);

 

  });

 

  loadResouces() {

    this.observable.subscribe(items => {

      this.scheduler.instance.option('resources[0].dataSource', items);

    });

  }

 

  constructor() { }

 

  ngOnInit(): void {

    this.loadResouces();

  }

 

}

**Comment by AryamnovEugeniy** [comment]
Thank you for your sample! I reproduced the issue, we will research it.

**Comment by bobskigit** [comment]
Now works in Sprint 9.

thanks
