### ISSUE TITLE
Error when installing as npm  package.

### ISSUE THREAD

**Issue by fizikst** [DevExpress/DevExtreme#3593]
[Example with button](https://github.com/DevExpress/devextreme-examples/tree/18_1/webpack-jquery) does not work for version 17.2.7, return error : "dxButton is not a function", and it works with version 17.1.3.

**Comment by AlekseyMartynov** [comment]
The example works fine on our side.
Make sure you are on the matching branch of the `devextreme-examples` repo:

`git checkout 17_2`

**Comment by fizikst** [comment]
Thanks,  it issue solved.
It not work:
"
var $ = require('jquery');
var dialog = require('devextreme/ui/dialog');
require('devextreme/ui/button');
...
"

It work : 
"
var $ = require('jquery');
var dialog = require('devextreme/ui/dialog');
**require('devextreme/integration/jquery');**
require('devextreme/ui/button');
...
"

**Comment by AlekseyMartynov** [comment]
This is a documented breaking change.
Check items **BC4148** & **BC4150** in [Breaking changes introduced in 17.2.3](https://www.devexpress.com/Support/Center/VersionHistory?TechnologyName=DevExtreme&PlatformName=AllPlatforms&ProductName=AllProducts&VersionHistoryItemsType=BreakingChanges&StartBuildName=17.2.3&EndBuildName=17.2.3&version-mode=single-mode)
